name: Generate Snake

on:
  workflow_dispatch:  # Permite ejecución manual desde Actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create dist folder
        run: mkdir -p dist

      - name: Generate snake.svg
        run: |
          echo '<svg width="100" height="100" xmlns="http://www.w3.org/2000/svg">
          <rect width="100" height="100" fill="lightgreen"/>
          <circle cx="50" cy="50" r="40" fill="darkgreen"/>
          </svg>' > dist/snake.svg

      - name: Commit and push to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/snake.svg
          git commit -m "Add snake.svg [skip ci]" || echo "No changes to commit"
          git branch -M output
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} output
