name: Generate Snake

on:
  workflow_dispatch: # Permite ejecución manual

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up directories
        run: |
          mkdir -p dist

      - name: Generate snake.svg
        run: |
          cat << 'EOF' > dist/snake.svg
<svg width="100" height="100" xmlns="http://www.w3.org/2000/svg">
  <rect width="100" height="100" fill="lightgreen"/>
  <circle cx="50" cy="50" r="40" fill="darkgreen"/>
</svg>
EOF

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          folder: dist
          target_branch: output
          github_token: ${{ secrets.GITHUB_TOKEN }}
