name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Corre cada 12 horas
  workflow_dispatch: # Permite correrlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: flarxx
          outputs: dist/snake.svg

      - name: Push snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
